## Importing the dataset

In [174]:
import pandas as pd

df=pd.read_csv("Inter_dataset_PII_masked.csv")
pd.set_option('display.max_columns', None)

## Check any nulls and data types

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   "company"                 754 non-null    object
 1   "creation_date"           754 non-null    object
 2   "approve_date"            619 non-null    object
 3   "closed_date"             566 non-null    object
 4   "po_no"                   754 non-null    int64
 5   "po_status"               754 non-null    object
 6   "line_num"                754 non-null    int64
 7   "line_type"               754 non-null    object
 8   "item_number"             454 non-null    float64
 9   "item_description"        754 non-null    object
 10  "inventory_type"          453 non-null    object
 11  "main_category"           453 non-null    object
 12  "group_category"          454 non-null    object
 13  "sub_group_category"      693 non-null    object
 14  "sub_sub_group_category"  0 non-null      float64
 15  "uom"                     754 non-null    object
 16  "buyer_name"              754 non-null    object
 17  "vendor_no"               752 non-null    float64
 18  "vendor_name"             752 non-null    object
 19  "payment_term"            632 non-null    object
 20  "vendor_site_code"        752 non-null    object
 21  "closed_code"             754 non-null    object
 22  "header_cancel"           754 non-null    object
 23  "line_cancel"             754 non-null    object
 24  "quantity_received"       754 non-null    float64
 25  "quantity_accepted"       754 non-null    float64
 26  "quantity_rejected"       754 non-null    int64
 27  "quantity_cancelled"      754 non-null    int64
 28  "currency_code"           754 non-null    object
 29  "rate"                    754 non-null    float64
 30  "quantity"                754 non-null    float64
 31  "unit_price"              754 non-null    float64
 32  "amount"                  754 non-null    float64
 33  "amount_egp"              754 non-null    float64
dtypes: float64(10), int64(4), object(20)
memory usage: 200.4+ KB

Company : organization that created the order

creation : date which order is created

approve :same

closed: order is done

po_no : order number

po_status :rejected or approved or incomplete

line_num : number of items in the same order

line type : categories of things ordered

item number :code of the item

item description : desciption 

uom : unit of measurment

currency code : العملة

rate : amount*rate = amount_egp

unit price : price of 1 item

quantity : elkmya 

quantity_received

quantity_accepted

quantity_rejected

quantity_cancelled

payment_term : how payment is done 

vendor_site_code : location code of the vendor

header_cancel : if order has been cancelled

line_cancel : if line was cancelled

In [176]:
df.columns = df.columns.str.replace('"', '', regex=False)
df = df.drop("sub_sub_group_category", axis=1)

In [177]:
print(df.isnull().sum())

company                 0
creation_date           0
approve_date          135
closed_date           188
po_no                   0
po_status               0
line_num                0
line_type               0
item_number           300
item_description        0
inventory_type        301
main_category         301
group_category        300
sub_group_category     61
uom                     0
buyer_name              0
vendor_no               2
vendor_name             2
payment_term          122
vendor_site_code        2
closed_code             0
header_cancel           0
line_cancel             0
quantity_received       0
quantity_accepted       0
quantity_rejected       0
quantity_cancelled      0
currency_code           0
rate                    0
quantity                0
unit_price              0
amount                  0
amount_egp              0
dtype: int64

In [178]:
df["approve_date"]=pd.to_datetime(df["approve_date"])
df["creation_date"]=pd.to_datetime(df["creation_date"])
df["closed_date"]=pd.to_datetime(df["closed_date"])

In [179]:
# Rejected purchase orders
df.loc[
    (df["po_status"] == "Rejected") & (df["approve_date"].isna()),
    "approve_date"
] = "Rejected"

df.loc[
    (df["po_status"] == "Rejected") & (df["closed_date"].isna()),
    "closed_date"
] = "Rejected"

# Incomplete purchase orders
df.loc[
    (df["po_status"] == "Incomplete") & (df["approve_date"].isna()),
    "approve_date"
] = "Not Approved"

df.loc[
    (df["po_status"] == "Incomplete") | (df["po_status"] == "Approved") & (df["closed_date"].isna())  ,
    "closed_date"
] = "Not Closed"

C:\Users\HP\AppData\Local\Temp\ipykernel_31400\2515269349.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rejected' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df.loc[
C:\Users\HP\AppData\Local\Temp\ipykernel_31400\2515269349.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rejected' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df.loc[

In [180]:
print(df.isnull().sum())

company                 0
creation_date           0
approve_date            0
closed_date             0
po_no                   0
po_status               0
line_num                0
line_type               0
item_number           300
item_description        0
inventory_type        301
main_category         301
group_category        300
sub_group_category     61
uom                     0
buyer_name              0
vendor_no               2
vendor_name             2
payment_term          122
vendor_site_code        2
closed_code             0
header_cancel           0
line_cancel             0
quantity_received       0
quantity_accepted       0
quantity_rejected       0
quantity_cancelled      0
currency_code           0
rate                    0
quantity                0
unit_price              0
amount                  0
amount_egp              0
dtype: int64

In [181]:
print(df["po_status"].value_counts())

print(df["line_type"].value_counts())

print(df["inventory_type"].value_counts())

print(df["currency_code"].value_counts())

po_status
Approved               617
Rejected               133
Incomplete               2
Requires Reapproval      2
Name: count, dtype: int64
line_type
Goods     455
Direct    191
Capex     108
Name: count, dtype: int64
inventory_type
Spare parts            405
Lubricants              15
Refractory               9
Bags (for packing)       7
Wear parts               5
Production supplies      4
Strategic                4
Safety                   4
Name: count, dtype: int64
currency_code
EGP    665
EUR     55
USD     30
GBP      3
AED      1
Name: count, dtype: int64

In [182]:
df.fillna({
    "item_number": "Unknown",
    "inventory_type": "Unknown",
    "main_category": "Unknown",
    "group_category": "Unknown",
    "sub_group_category": "Unknown",
    "vendor_no" : "Unknown",
    "vendor_name":"Unknown",
    "payment_term":"Unknown",
    "vendor_site_code":"Unknown" }, inplace=True)

In [183]:
df.head()

,company,creation_date,approve_date,closed_date,po_no,po_status,line_num,line_type,item_number,item_description,inventory_type,main_category,group_category,sub_group_category,uom,buyer_name,vendor_no,vendor_name,payment_term,vendor_site_code,closed_code,header_cancel,line_cancel,quantity_received,quantity_accepted,quantity_rejected,quantity_cancelled,currency_code,rate,quantity,unit_price,amount,amount_egp
0,ASF,2019-06-27,2019-08-06 00:00:00,2019-09-26 12:24:16,190394,Approved,1,Goods,4030305944.0,"Ring, scatter ring, diameter 5860/6200, thickn...",Wear parts,Mechanical items,mechanical items for cement grinding area (500),Scatter ring for cement mill dam ring,Each,Buyer_05,9019.0,Vendor_059,14 days,Site_066,CLOSED,Valid,Valid,24.0,24.0,0,0,EGP,1.0,24.0,3700.0,88800.0,88800.0
1,EGYLUX,2019-06-27,2019-07-18 00:00:00,2019-09-03 11:57:43,190395,Approved,1,Goods,3060411366.0,"Pump, centrifugal, water, type 3LM 50-200/11 ,...",Spare parts,Mechanical items,mechanical items for utilities area (700),Pump,Each,Buyer_03,9068.0,Vendor_122,14 days,Site_045,CLOSED,Valid,Valid,2.0,2.0,0,0,EGP,1.0,2.0,26220.0,52440.0,52440.0
2,ESCC,2019-06-27,2019-07-10 00:00:00,2019-07-31 16:52:24,190396,Approved,1,Goods,3030201129.0,"Belt, V-belt type, SPB 1250",Spare parts,Mechanical items,V-belt items,V-belt,Each,Buyer_03,9079.0,Vendor_111,14 days,Site_046,CLOSED,Valid,Valid,6.0,6.0,0,0,EGP,1.0,6.0,86.0,516.0,516.0
3,ASF,2019-06-27,2019-07-30 00:00:00,2019-11-04 15:50:53,190397,Approved,1,Goods,3040209714.0,"Valve, directional control valve, type DG17V-3...",Spare parts,Mechanical items,mechanical items for raw materials handling ar...,Valve,Each,Buyer_03,9099.0,Vendor_112,14 days,Site_080,CLOSED,Valid,Valid,1.0,1.0,0,0,EGP,1.0,1.0,5320.0,5320.0,5320.0
4,ASF,2019-06-26,2019-07-30 00:00:00,2019-12-03 16:04:57,190384,Approved,1,Direct,Unknown,"Rod, round, diameter 090 mm, recommended lengt...",Unknown,Unknown,Unknown,Brass for control gate.,Each,Buyer_01,9124.0,Vendor_134,Immediate,Site_016,CLOSED,Valid,Valid,1.0,1.0,0,0,EGP,1.0,1.0,9690.0,9690.0,9690.0

In [184]:
cat_column = [cols for cols in df.columns if(df[cols].dtype =='object') ]
num_column = [cols for cols in df.columns if(df[cols].dtype !='object') ]

print(cat_column)
print(num_column)

['company', 'approve_date', 'closed_date', 'po_status', 'line_type', 'item_number', 'item_description', 'inventory_type', 'main_category', 'group_category', 'sub_group_category', 'uom', 'buyer_name', 'vendor_no', 'vendor_name', 'payment_term', 'vendor_site_code', 'closed_code', 'header_cancel', 'line_cancel', 'currency_code']
['creation_date', 'po_no', 'line_num', 'quantity_received', 'quantity_accepted', 'quantity_rejected', 'quantity_cancelled', 'rate', 'quantity', 'unit_price', 'amount', 'amount_egp']

In [185]:

df.head()

,company,creation_date,approve_date,closed_date,po_no,po_status,line_num,line_type,item_number,item_description,inventory_type,main_category,group_category,sub_group_category,uom,buyer_name,vendor_no,vendor_name,payment_term,vendor_site_code,closed_code,header_cancel,line_cancel,quantity_received,quantity_accepted,quantity_rejected,quantity_cancelled,currency_code,rate,quantity,unit_price,amount,amount_egp
0,ASF,2019-06-27,2019-08-06 00:00:00,2019-09-26 12:24:16,190394,Approved,1,Goods,4030305944.0,"Ring, scatter ring, diameter 5860/6200, thickn...",Wear parts,Mechanical items,mechanical items for cement grinding area (500),Scatter ring for cement mill dam ring,Each,Buyer_05,9019.0,Vendor_059,14 days,Site_066,CLOSED,Valid,Valid,24.0,24.0,0,0,EGP,1.0,24.0,3700.0,88800.0,88800.0
1,EGYLUX,2019-06-27,2019-07-18 00:00:00,2019-09-03 11:57:43,190395,Approved,1,Goods,3060411366.0,"Pump, centrifugal, water, type 3LM 50-200/11 ,...",Spare parts,Mechanical items,mechanical items for utilities area (700),Pump,Each,Buyer_03,9068.0,Vendor_122,14 days,Site_045,CLOSED,Valid,Valid,2.0,2.0,0,0,EGP,1.0,2.0,26220.0,52440.0,52440.0
2,ESCC,2019-06-27,2019-07-10 00:00:00,2019-07-31 16:52:24,190396,Approved,1,Goods,3030201129.0,"Belt, V-belt type, SPB 1250",Spare parts,Mechanical items,V-belt items,V-belt,Each,Buyer_03,9079.0,Vendor_111,14 days,Site_046,CLOSED,Valid,Valid,6.0,6.0,0,0,EGP,1.0,6.0,86.0,516.0,516.0
3,ASF,2019-06-27,2019-07-30 00:00:00,2019-11-04 15:50:53,190397,Approved,1,Goods,3040209714.0,"Valve, directional control valve, type DG17V-3...",Spare parts,Mechanical items,mechanical items for raw materials handling ar...,Valve,Each,Buyer_03,9099.0,Vendor_112,14 days,Site_080,CLOSED,Valid,Valid,1.0,1.0,0,0,EGP,1.0,1.0,5320.0,5320.0,5320.0
4,ASF,2019-06-26,2019-07-30 00:00:00,2019-12-03 16:04:57,190384,Approved,1,Direct,Unknown,"Rod, round, diameter 090 mm, recommended lengt...",Unknown,Unknown,Unknown,Brass for control gate.,Each,Buyer_01,9124.0,Vendor_134,Immediate,Site_016,CLOSED,Valid,Valid,1.0,1.0,0,0,EGP,1.0,1.0,9690.0,9690.0,9690.0

In [186]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   company             754 non-null    object
 1   creation_date       754 non-null    datetime64[ns]
 2   approve_date        754 non-null    object
 3   closed_date         754 non-null    object
 4   po_no               754 non-null    int64
 5   po_status           754 non-null    object
 6   line_num            754 non-null    int64
 7   line_type           754 non-null    object
 8   item_number         754 non-null    object
 9   item_description    754 non-null    object
 10  inventory_type      754 non-null    object
 11  main_category       754 non-null    object
 12  group_category      754 non-null    object
 13  sub_group_category  754 non-null    object
 14  uom                 754 non-null    object
 15  buyer_name          754 non-null    object
 16  vendor_no           754 non-null    object
 17  vendor_name         754 non-null    object
 18  payment_term        754 non-null    object
 19  vendor_site_code    754 non-null    object
 20  closed_code         754 non-null    object
 21  header_cancel       754 non-null    object
 22  line_cancel         754 non-null    object
 23  quantity_received   754 non-null    float64
 24  quantity_accepted   754 non-null    float64
 25  quantity_rejected   754 non-null    int64
 26  quantity_cancelled  754 non-null    int64
 27  currency_code       754 non-null    object
 28  rate                754 non-null    float64
 29  quantity            754 non-null    float64
 30  unit_price          754 non-null    float64
 31  amount              754 non-null    float64
 32  amount_egp          754 non-null    float64
dtypes: datetime64[ns](1), float64(7), int64(4), object(21)
memory usage: 194.5+ KB
None
company               0
creation_date         0
approve_date          0
closed_date           0
po_no                 0
po_status             0
line_num              0
line_type             0
item_number           0
item_description      0
inventory_type        0
main_category         0
group_category        0
sub_group_category    0
uom                   0
buyer_name            0
vendor_no             0
vendor_name           0
payment_term          0
vendor_site_code      0
closed_code           0
header_cancel         0
line_cancel           0
quantity_received     0
quantity_accepted     0
quantity_rejected     0
quantity_cancelled    0
currency_code         0
rate                  0
quantity              0
unit_price            0
amount                0
amount_egp            0
dtype: int64

### Columns carrying meanings
- Company
- po-status
- line-type
- item-description
- Inventory Type
- Main Category
- Group Category
- Sub Group Category
- buyer-name
- vendor-name
- payment term
- quantity
- currency code
- amount
- unit price
- rate
- uom
- closed code
  

### Columns are meta data
- creation_date      
- approve_date        
- closed_date 
- po number
- vendor no
- item number
- line number
- vendor site code
- header cancel 
- item cancel
- quantity_received     
- quantity_accepted     
- quantity_rejected     
- quantity_cancelled  
- amount_egp